development:
  adapter: postgresql
  encoding: unicode
  database: guardiadiporta
  pool: 5
  #username: myapp
  #password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: guardiadiporta_test
  pool: 5
  #username: myapp
  #password: password1
