# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c5adfeeed3b8e4581a1aa0e95bdff0f3dd9d0ddc47eafccae66d9d89e52fbea8c920253aba31b3cb145126aba5a5cb91862570cddcf5a9bab7df8d8121a810c

test:
  secret_key_base: ae603d417f0894d0f0005558a0084db9cb395addfe81edfd669a4e86c266b652505fdd9097119319875d27659ea8e695d873f7bacb6ccbdbf394ba1f750b8e9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
